### ISSUE TITLE
srccd: Some Dataframes can not use matplotlib

### ISSUE THREAD

**Issue by Andrew95496** [Andrew95496/cobra#12]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/axis.py", line 1506, in convert_units
    ret = self.converter.convert(x, self.units, self)
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/category.py", line 49, in convert
    raise ValueError(
ValueError: Missing category information for StrCategoryConverter; this might be caused by unintendedly mixing categorical and numeric data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.9/3.9.13_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/Users/drewskikatana/Documents/Programming/cobra/Objects/plot_object.py", line 26, in <lambda>
    my_button = Button(root, text=name, command=lambda data = self.data_dict[name]: self._create_graph(data))
  File "/Users/drewskikatana/Documents/Programming/cobra/Objects/plot_object.py", line 15, in _create_graph
    plt.hist(data)
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/pyplot.py", line 2590, in hist
    return gca().hist(
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 6560, in hist
    x = [*self._process_unit_info([("x", x[0])], kwargs),
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/artist.py", line 252, in convert_xunits
    return ax.xaxis.convert_units(x)
  File "/opt/homebrew/lib/python3.9/site-packages/matplotlib/axis.py", line 1508, in convert_units
    raise munits.ConversionError('Failed to convert value(s) to axis '
matplotlib.units.ConversionError: Failed to convert value(s) to axis units: array(['Abu Dhabi', 'Abu Dhabi', 'Abu Dhabi', 'Abu Dhabi', 'São Paulo',
       'Long Beach', 'Trenton', 'Barcelona', 'Nottingham', 'Beijing',
       'São Paulo', 'Espoo', 'Anaheim'], dtype=object)

```

**Comment by Andrew95496** [comment]
# Extra Info:

It seems like not all tables acquired from a scrap are able to be shown as a histogram. 

TODO: Create an algorithm to determine the type of data the table is and use a graph to fit the appropriate data type.

**Comment by Andrew95496** [comment]
No Longer using Matplotlib
